### ISSUE TITLE
Import changelog from another project

### ISSUE THREAD

**Issue by hueniverse** [creativelive/mdchangelog#21]
This is a bit nuts but would be incredibly useful.

I'm moving hapi to use absolute versions and shrinkwrap. This will require opening an issue for every dependency upgrade. It would be ideal if instead of having just a line with "#123 upgrade hoek to 2.3.4" it will also include all the changes in hoek that this imports. To make it easier, I could always include the from and to versions in the title. These are also always labels with 'dependency'.

Ideas?

**Comment by diffsky** [comment]
this was fixed
