### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by AdriVanHoudt** [creativelive/mdchangelog#25]
I get a `ENOENT` error when generating the changelog for `Hapi`.  
```bash
[//github.com/AdriVanHoudt/hapi] fetching 1311/1311 issues [====================] 100% 0.0s
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
{ [Error: ENOENT, mkdir 'c:\tmp\mdchangelog-CLTDWIM']
  errno: -4058,
  code: 'ENOENT',
  path: 'c:\\tmp\\mdchangelog-CLTDWIM' }
Makefile:8: recipe for target 'changelog' failed
make: *** [changelog] Error 1
```

**Comment by diffsky** [comment]
I guess there is no `c:\tmp` directory for mdchangelog to write to :-/ 

I can't guarantee that things are going to work on windows unfortunately. Can you test this on linux or osx?

https://github.com/sasaplus1/mktemp is being used to create the directory:
https://github.com/creativelive/mdchangelog/blob/5bb87ad964ea44097229a23ba1c612f03d656f3e/lib/runner.js#L60

The prefixed `/tmp` is probably at fault. I'm not sure where mktemp creates the directory without that prefix, but you could try playing around with that and see what the results are.

**Comment by AdriVanHoudt** [comment]
I do have a temp folder but it's `C:\temp` maybe the capital `C` does the thing? I'll try some stuff

**Comment by diffsky** [comment]
Looks like mdchangelog is workiong (on OSX) but you're likely to run into https://github.com/creativelive/mdchangelog/issues/24

```
$ MDCHANGELOG_TOKEN=$(keychain -g GITHUB_TOKEN) make changelog
[hapijs/hapi] fetching 1312/1312 issues [====================] 100% 0.0s
[hapijs/catbox] fetching 78/78 issues [====================] 100% 0.0s
[hapijs/boom] fetching 31/31 issues [====================] 100% 0.0s
[hapijs/shot] fetching 14/14 issues [====================] 100% 0.0s
[hapijs/joi] fetching 304/304 issues [====================] 100% 0.0s
[hapijs/call] fetching 7/7 issues [====================] 100% 0.0s
[hapijs/hoek] fetching 91/91 issues [====================] 100% 0.0s
[hapijs/joi] fetching 304/304 issues [====================] 100% 0.0s
[hapijs/catbox] fetching 78/78 issues [====================] 100% 0.0s
[hapijs/mimos] fetching 7/7 issues [====================] 100% 0.0s
[hapijs/qs] fetching 43/43 issues [====================] 100% 0.0s
[hapijs/boom] fetching 31/31 issues [====================] 100% 0.0s

/Users/mhadley/dev/nodejs/mdchangelog/node_modules/semver/semver.js:273
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: 6.0
    at new SemVer (/Users/mhadley/dev/nodejs/mdchangelog/node_modules/semver/semver.js:273:11)
    at compare (/Users/mhadley/dev/nodejs/mdchangelog/node_modules/semver/semver.js:493:10)
    at Function.gt (/Users/mhadley/dev/nodejs/mdchangelog/node_modules/semver/semver.js:522:10)
    at /Users/mhadley/dev/nodejs/mdchangelog/lib/formatter.js:27:20
    at Array.forEach (native)
    at findDependents (/Users/mhadley/dev/nodejs/mdchangelog/lib/formatter.js:26:43)
    at formatIssue (/Users/mhadley/dev/nodejs/mdchangelog/lib/formatter.js:41:3)
    at /Users/mhadley/dev/nodejs/mdchangelog/lib/formatter.js:60:14
    at Array.forEach (native)
    at /Users/mhadley/dev/nodejs/mdchangelog/lib/formatter.js:59:27
    at Array.forEach (native)
make: *** [changelog] Error 8
```

This is where some of the milestones referenced aren't valid semver numbers. I'll have to add some more debug output to track down the culprit, but I've likely exhausted the github api quota :)

**Comment by AdriVanHoudt** [comment]
I'm running Windows and yeah I can only test like 3 times per hour :D and can't you do what Eran suggested? Fail and just set the title to that 'version'?

**Comment by diffsky** [comment]
that number is used for ordering, so I'd have to "fix" it. My concern was about how far I go in attempting the fix. I can try adding a `.0` for the `x.x` case and see how far that gets things.

**Comment by AdriVanHoudt** [comment]
Ok yeah that poses a problem then. Wouldn't `x.y` to `x.y.z` solve most of the cases?

**Comment by diffsky** [comment]
> Ok yeah that poses a problem then. Wouldn't x.y to x.y.z solve most of the cases?

Hopefully! I can add that in and see. In general I recommend these "dependent" changelogs only be generated for repos that you control, which means you can control having a semver compliant milestone.

**Comment by AdriVanHoudt** [comment]
If it fails on Hapi than I'll notify Eran

**Comment by diffsky** [comment]
This is the milestone causing the problem:
https://github.com/hapijs/joi/milestones/6.0

**Comment by AdriVanHoudt** [comment]
Can you rename milestones?

**Comment by diffsky** [comment]
Maybe @hueniverse can get the joi milestone corrected until I get time to make mdchangelog's semver checking more relaxed.

**Comment by AdriVanHoudt** [comment]
Pinging @marsup because he is the lead maintainer of Joi

**Comment by AdriVanHoudt** [comment]
But back to the point of this issue, I'm only trying to make the changelog for `hapijs/hapi`.
I was able to fix the error by giving the right rights for the tmp folder but I still get 
```bash
[//github.com/AdriVanHoudt/hapi] fetching 1311/1311 issues [====================] 100% 0.0s
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
```
And the changelog only includes 
```markdown
## [**2.1.0**](https://github.com///github.com/AdriVanHoudt/hapi/issues?milestone=4&state=closed)
- [**#hapijs/inert#17**](https://github.com/hapijs/inert/issues/17) Handle Range requests explicitly
```
Is this because of milestone 4 or something?

**Comment by Marsup** [comment]
It's now renamed on joi.

**Comment by diffsky** [comment]
> I'm only trying to make the changelog for `hapijs/hapi`

As requested in https://github.com/creativelive/mdchangelog/issues/21, mdchangelog will pull in changelogs of repos that are marked as dependencies. It'll clone those dependencies and build their changelog (so maybe you're hitting the same issue again, I haven't dug into it).

After the milestone renaming (thanks @Marsup) I successfully generated a changelog:
https://gist.github.com/diffsky/73f62e1430d84c16d51b
(notice the embedded changelogs for dependencies)

**Comment by AdriVanHoudt** [comment]
Ah like that, is it possible that the lib does not throw errors because I don't see them. And thanks for generating one. 
1 comment. 8.2.1 is not closed yet. Should it be in the changelog already? It is 100% though.

**Comment by diffsky** [comment]
8.2.1 is pulled in because it contains a closed issue. It might be worth mdchangelog having a flag to only include closed milestones.

I'm not sure why your generate stopped early, I would have expected to see some errors thrown. It also looks like it generated a broken link: `https://github.com///github.com/AdriVanHoudt/hapi`

Shot in the dark, did you originally clone hapi via https? If so can you try ssh?

**Comment by AdriVanHoudt** [comment]
I see and yeah I would guess it should only include closed milestones. 

I did clone via https, let me try ssh

**Comment by AdriVanHoudt** [comment]
Tried ssh same result :neutral_face:
