### ISSUE TITLE
Consider adding a flag to restrict dependent repos to the same github org

### ISSUE THREAD

**Issue by diffsky** [creativelive/mdchangelog#30]
see https://github.com/hapijs/hapi/issues/2525

**Comment by AdriVanHoudt** [comment]
For reference this is mainly to prevent outside org repos to break the generation of the changelog because of malformed data like non-semver matching tags

**Comment by diffsky** [comment]
```
+ mdchangelog@0.7.0
```

Added `--same-org` to restrict to the same github org.
