### ISSUE TITLE
An option to escape some characters in commit messages

### ISSUE THREAD

**Issue by mtharrison** [creativelive/mdchangelog#31]
Would you consider an option to escape some characters in commit messages?

Consider this md fragment. When it's converted to HTML by github, 2551 should be in the list above 73. But 73 is swallowing it up because of \<Object\>.

Markdown:
```
## [**8.5.0**](https://github.com/hapijs/hapi/issues?milestone=139&state=closed)
- [**#2481**](https://github.com/hapijs/hapi/issues/2481) Feature: server.decorate('request' ... )
- [**#2544**](https://github.com/hapijs/hapi/issues/2544) Retain content-length header for HEAD requests
- [**#2552**](https://github.com/hapijs/hapi/issues/2552) Update hapijs/wreck to 5.5.1 from 5.2.0
  - **hapijs/wreck 5.5.0**
  - [**#81**](https://github.com/hapijs/wreck/issues/81) Added uri to event payloads.
  - **hapijs/wreck 5.4.0**
  - [**#79**](https://github.com/hapijs/wreck/issues/79) Add start time to response event
  - **hapijs/wreck 5.3.0**
  - [**#77**](https://github.com/hapijs/wreck/issues/77) Add event for response and logging
  - [**#73**](https://github.com/hapijs/wreck/issues/73) Fix issues with node 0.12
- [**#2472**](https://github.com/hapijs/hapi/issues/2472) Update hapijs/qs to 2.4.2 from 2.4.0
  - **hapijs/qs 2.4.1**
  - [**#73**](https://github.com/hapijs/qs/issues/73) Property 'hasOwnProperty' of object <Object> is not a function
- [**#2551**](https://github.com/hapijs/hapi/issues/2551) Update jshttp/mime-db to 1.10.0 from 1.9.1
- [**#2550**](https://github.com/hapijs/hapi/issues/2550) Update moment/moment to 2.10.3 from 2.9.0
- [**#2549**](https://github.com/hapijs/hapi/issues/2549) Update hapijs/joi to 6.4.1 from 6.0.8
  - **hapijs/joi 6.4.0**
  - [**#629**](https://github.com/hapijs/joi/issues/629) help with `.or()`
  - **hapijs/joi 6.2.0**
  - [**#413**](https://github.com/hapijs/joi/issues/413) Create default [highly nested] object easily?
  - **hapijs/joi 6.1.2**
  - [**#628**](https://github.com/hapijs/joi/issues/628) Alternatives throw typeError when "is: null" is used
  - **hapijs/joi 6.1.1**
  - [**#627**](https://github.com/hapijs/joi/issues/627) Property is always required even when my When() condition isn't met.
  - **hapijs/joi 6.1.0**
 ```
HTML:

## [**8.5.0**](https://github.com/hapijs/hapi/issues?milestone=139&state=closed)
- [**#2481**](https://github.com/hapijs/hapi/issues/2481) Feature: server.decorate('request' ... )
- [**#2544**](https://github.com/hapijs/hapi/issues/2544) Retain content-length header for HEAD requests
- [**#2552**](https://github.com/hapijs/hapi/issues/2552) Update hapijs/wreck to 5.5.1 from 5.2.0
  - **hapijs/wreck 5.5.0**
  - [**#81**](https://github.com/hapijs/wreck/issues/81) Added uri to event payloads.
  - **hapijs/wreck 5.4.0**
  - [**#79**](https://github.com/hapijs/wreck/issues/79) Add start time to response event
  - **hapijs/wreck 5.3.0**
  - [**#77**](https://github.com/hapijs/wreck/issues/77) Add event for response and logging
  - [**#73**](https://github.com/hapijs/wreck/issues/73) Fix issues with node 0.12
- [**#2472**](https://github.com/hapijs/hapi/issues/2472) Update hapijs/qs to 2.4.2 from 2.4.0
  - **hapijs/qs 2.4.1**
  - [**#73**](https://github.com/hapijs/qs/issues/73) Property 'hasOwnProperty' of object <Object> is not a function
- [**#2551**](https://github.com/hapijs/hapi/issues/2551) Update jshttp/mime-db to 1.10.0 from 1.9.1
- [**#2550**](https://github.com/hapijs/hapi/issues/2550) Update moment/moment to 2.10.3 from 2.9.0
- [**#2549**](https://github.com/hapijs/hapi/issues/2549) Update hapijs/joi to 6.4.1 from 6.0.8
  - **hapijs/joi 6.4.0**
  - [**#629**](https://github.com/hapijs/joi/issues/629) help with `.or()`
  - **hapijs/joi 6.2.0**
  - [**#413**](https://github.com/hapijs/joi/issues/413) Create default [highly nested] object easily?
  - **hapijs/joi 6.1.2**
  - [**#628**](https://github.com/hapijs/joi/issues/628) Alternatives throw typeError when "is: null" is used
  - **hapijs/joi 6.1.1**
  - [**#627**](https://github.com/hapijs/joi/issues/627) Property is always required even when my When() condition isn't met.
  - **hapijs/joi 6.1.0**

**Comment by diffsky** [comment]
would escaping all angle brackets be enough?

**Comment by mtharrison** [comment]
That would be awesome, yes. Thanks.

**Comment by diffsky** [comment]
I've added a `--sanitize` option that escapes angle brackets in the output
```
+ mdchangelog@0.8.0
```

**Comment by mtharrison** [comment]
:tada:
